from detectron2.config.defaults import _C
from detectron2.config import CfgNode as CN

_CC = _C

# --------Solver------
_CC.SOLVER.OPTIMIZER = "SGD"

# ----------- Backbone ----------- #
_CC.MODEL.BACKBONE.FREEZE = False
_CC.MODEL.BACKBONE.FREEZE_AT = 3

# ------------- SwinT ------------ #
_CC.MODEL.SWINT = CN()
_CC.MODEL.SWINT.EMBED_DIM = 96
_CC.MODEL.SWINT.OUT_FEATURES = ["stage2", "stage3", "stage4", "stage5"]
_CC.MODEL.SWINT.DEPTHS = [2, 2, 6, 2]
_CC.MODEL.SWINT.NUM_HEADS = [3, 6, 12, 24]
_CC.MODEL.SWINT.WINDOW_SIZE = 7
_CC.MODEL.SWINT.MLP_RATIO = 4
_CC.MODEL.SWINT.DROP_PATH_RATE = 0.2
_CC.MODEL.SWINT.APE = False

# ------------- RPN -------------- #
_CC.MODEL.RPN.FREEZE = False
_CC.MODEL.RPN.ENABLE_DECOUPLE = False
_CC.MODEL.RPN.BACKWARD_SCALE = 1.0

# ------------- ROI -------------- #
_CC.MODEL.ROI_HEADS.NAME = "Res5ROIHeads"
_CC.MODEL.ROI_HEADS.FREEZE_FEAT = False
_CC.MODEL.ROI_HEADS.ENABLE_DECOUPLE = False
_CC.MODEL.ROI_HEADS.BACKWARD_SCALE = 1.0
_CC.MODEL.ROI_HEADS.OUTPUT_LAYER = "FastRCNNOutputLayers"
_CC.MODEL.ROI_HEADS.CLS_DROPOUT = False
_CC.MODEL.ROI_HEADS.DROPOUT_RATIO = 0.8
_CC.MODEL.ROI_BOX_HEAD.POOLER_RESOLUTION = 7  # for faster

# ------------- TEST ------------- #
_CC.TEST.PCB_ENABLE = False
_CC.TEST.PCB_MODELTYPE = 'resnet'             # res-like
_CC.TEST.PCB_MODELPATH = ""
_CC.TEST.PCB_ALPHA = 0.50
_CC.TEST.PCB_UPPER = 1.0
_CC.TEST.PCB_LOWER = 0.05

# ------------ Other ------------- #
_CC.SOLVER.WEIGHT_DECAY = 5e-5
_CC.MUTE_HEADER = True

# ------------ MFDC ------------- #
_CC.DATASETS.TWO_STREAM = False
_CC.MODEL.ROI_HEADS.MEMORY = False
_CC.MODEL.ROI_HEADS.AUGMENTATION = False
_CC.MODEL.ROI_HEADS.SEMANTIC = False
_CC.MODEL.ROI_HEADS.WARMUP_DISTILL = 200
_CC.MODEL.ROI_HEADS.QUEUE_LEN = 2048

# ------------- KGC -------------- #
_CC.KGC = CN()
_CC.KGC.SHOTS = 1
_CC.KGC.CONTAINER = 4
_CC.KGC.FEATURE_DIM = 128
_CC.KGC.KNOWLEDGE_MATRIX = None
_CC.KGC.TAU = 0.2
_CC.KGC.COEF = 1.0

# Explanation Operation
_CC.COUNTERFACTUAL = CN()
_CC.COUNTERFACTUAL.OPERATOR = False
_CC.COUNTERFACTUAL.START_ITER = 1000
_CC.COUNTERFACTUAL.ERASE_THRESHOLD = 0.6
_CC.COUNTERFACTUAL.VISUALIZATION = False
_CC.COUNTERFACTUAL.COUNTER_NUMBER = 3
_CC.COUNTERFACTUAL.ERASE_RATE = 0.05
_CC.COUNTERFACTUAL.ERASE_METHOD = "random"