_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/coco/faster_rcnn/model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 80
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: False
    # IOU_THRESHOLDS: [0.60]
  BACKBONE:
    FREEZE: False
    FREEZE_AT: 5
  PROPOSAL_GENERATOR:
    FREEZE: False
DATASETS:
  TRAIN: ('coco_trainval_all_10shot',)
  TEST: ('coco_test_all',)
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
  CROP:
     ENABLED: True
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (20000,)
  MAX_ITER: 30000
  CHECKPOINT_PERIOD: 1000
  GAMMA: 0.3
  WARMUP_ITERS: 200
  # IMS_PER_BATCH: 16
  # BASE_LR: 0.001
  # STEPS: (144000,)
  # MAX_ITER: 160000
  # CHECKPOINT_PERIOD: 2000
  # WARMUP_ITERS: 10
TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 1000
  # IMS_PER_BATCH: 16
  # BASE_LR: 0.001
  # STEPS: (20000,)
  # MAX_ITER: 30000
  # CHECKPOINT_PERIOD: 1000
  # GAMMA: 0.3
  # WARMUP_ITERS: 200
SEED: 1
OUTPUT_DIR: "checkpoints/coco/ExAu/ExAu_R_101_FPN_ft_all_10shot"
KNOWLEDGE: True
KNOWLEDGE_MATRIX: "knowledge_matrix/text_relationship/coco/coco-word-embedding.npy"
CLUSTER: True
TAU: 0.2
SHOT: 10
NORM_MATRIX: "linear"  # [linear, exp, no]
BANK_CONTAINER: 4
COUNTERFACTUAL:
  OPERATOR: True
  START_ITER: 10
  ERASE_THRESHOLD: 0.8
  VISUALIZATION: False
  COUNTER_NUMBER: 5
  ERASE_RATE: 0.05
  ERASE_METHOD: "random"
LAMBDA1: 1.
LAMBDA2: 2.
LAMBDA3: 0.5