from detectron2.data.datasets.coco_zeroshot_categories import COCO_SEEN_CLS, \
    COCO_UNSEEN_CLS, COCO_OVD_ALL_CLS
from detectron2.data import MetadataCatalog

coco17_all_classes = MetadataCatalog.get('coco_2017_val').thing_classes

contiguous_id_to_thing_dataset_id = {countId: catId for catId, countId in MetadataCatalog.get('coco_2017_val').thing_dataset_id_to_contiguous_id.items()}

# Dataset Names
LVIS = "lvis_v1_train"
LVIS_FEW = "lvis_v1_few"
COCO_OVD = "coco_2017_ovd_b_train"

COCO_2017_SPLIT_1 = 'coco_2017_train_oneshot_s1'
COCO_2017_SPLIT_2 = 'coco_2017_train_oneshot_s2'
COCO_2017_SPLIT_3 = 'coco_2017_train_oneshot_s3'
COCO_2017_SPLIT_4 = 'coco_2017_train_oneshot_s4'

COCO_2014_FEW_SHOT = 'fs_coco14_base_train'
COCO_2017_FEW_SHOT = 'fs_coco17_base_train' # not used
COCO_2014_FEW_TEN_SHOT = 'fs_coco14_10shot_train'
COCO_2014_FEW_THIRTY_SHOT = 'fs_coco14_30shot_train'

FSOD1K_BASE = "fsod1k_base"
FSOD1K_5SHOT = "fsod1k_5shot"
FSOD1K_TEST = "fsod1k_test"

FSVOD_BASE = "fsvod_base"
FSVOD_5SHOT = "fsvod_5shot"
FSVOD_TEST = "fsvod_test"
FSVOD_TEST_ALL = "fsod1k_test_all"

VOC_BASE1 = "voc_base1"
VOC_TEST1 = "voc_test1"

VOC_BASE2 = "voc_base2"
VOC_TEST2 = "voc_test2"

VOC_BASE3 = "voc_base3"
VOC_TEST3 = "voc_test3"

VOC_SPLIT1_1 = "voc_split1_1"
VOC_SPLIT1_2 = "voc_split1_2"
VOC_SPLIT1_3 = "voc_split1_3"
VOC_SPLIT1_5 = "voc_split1_5"
VOC_SPLIT1_10 = "voc_split1_10"

VOC_SPLIT2_1 = "voc_split2_1"
VOC_SPLIT2_2 = "voc_split2_2"
VOC_SPLIT2_3 = "voc_split2_3"
VOC_SPLIT2_5 = "voc_split2_5"
VOC_SPLIT2_10 = "voc_split2_10"

VOC_SPLIT3_1 = "voc_split3_1"
VOC_SPLIT3_2 = "voc_split3_2"
VOC_SPLIT3_3 = "voc_split3_3"
VOC_SPLIT3_5 = "voc_split3_5"
VOC_SPLIT3_10 = "voc_split3_10"

fs_coco_2014_seen_classes = ['truck', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'bed', 'toilet', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush']
fsod_base_classes = ['lipstick',
 'sandal',
 'crocodile',
 'football helmet',
 'umbrella',
 'hartebeest',
 'houseplant',
 'modem',
 'antelope',
 'woodpecker',
 'palm tree',
 'shower cap',
 'mask',
 'box',
 'handkerchief',
 'falafel',
 'swan',
 'miniskirt',
 'monkey',
 'cookie',
 'scissors',
 'clipper',
 'snowboard',
 'croquette',
 'house finch',
 'hedgehog',
 'penguin',
 'barrel',
 'butterfly fish',
 'lesser scaup',
 'wall clock',
 'barbell',
 'hair slide',
 'strawberry',
 'window blind',
 'butterfly',
 'television',
 'arabian camel',
 'cake',
 'pill bottle',
 'springbok',
 'camper',
 'punching bag',
 'picture frame',
 'face powder',
 'jaguar',
 'basketball player',
 'tomato',
 'isopod',
 'balloon',
 'bumper car',
 'wisent',
 'hip',
 'vase',
 'shirt',
 'waffle',
 'carrot',
 'candle',
 'wicket',
 'flute',
 'medicine ball',
 'bagel',
 'orange',
 'wheelchair',
 'golf ball',
 'unicycle',
 'surfboard',
 'cattle',
 'parachute',
 'sweet orange',
 'snowshoe',
 'candy',
 'turkey',
 'pillow',
 'column',
 'king charles spaniel',
 'jacket',
 'crane',
 'scoter',
 'dumbbell',
 'dagger',
 'wine glass',
 'guitar',
 'slide rule',
 'steel drum',
 'sports car',
 'go kart',
 'shrimp',
 'worm',
 'hamburger',
 'cucumber',
 'gearing',
 'radish',
 'tostada',
 'french loaf',
 'granny smith',
 'sorrel',
 'ibex',
 'rain barrel',
 'quail',
 'alpaca',
 'rhodesian ridgeback',
 'mongoose',
 'red backed sandpiper',
 'penlight',
 'bicycle wheel',
 'shelf',
 'pancake',
 'samoyed',
 'helicopter',
 'pay phone',
 'barber chair',
 'perfume',
 'wool',
 'sword',
 'ballplayer',
 'ipod',
 'goose',
 'pretzel',
 'coin',
 'broccoli',
 'malamute',
 'reel',
 'mountain goat',
 'mule',
 'tusker',
 'cabbage',
 'longwool',
 'sheep',
 'apple',
 'flag',
 'shopping cart',
 'marble',
 'horse',
 'duck',
 'salad',
 'lemon',
 'handgun',
 'shuttlecock',
 'red breasted merganser',
 'shutter',
 'stamp',
 'backpack',
 'printer',
 'mug',
 'snowmobile',
 'boot',
 'bowl',
 'book',
 'tin can',
 'football',
 'human leg',
 'letter opener',
 'countertop',
 'elephant',
 'ladybug',
 'curtain',
 'wine',
 'canopic jar',
 'warthog',
 'van',
 'oil filter',
 'envelope',
 'pen',
 'petri dish',
 'bubble',
 'doll',
 'bus',
 'african crocodile',
 'bikini',
 'brambling',
 'siamang',
 'bison',
 'snorkel',
 'flying disc',
 'microwave oven',
 'stethoscope',
 'loafer',
 'burrito',
 'kite balloon',
 'wallet',
 'mushroom',
 'laundry cart',
 'teddy bear',
 'nail',
 'sausage dog',
 'bottle',
 'raccoon',
 'rifle',
 'peach',
 'king penguin',
 'laptop',
 'diver',
 'centipede',
 'rake',
 'tiger',
 'watch',
 'drake',
 'bald eagle',
 'cat',
 'ladder',
 'sparrow',
 'retriever',
 'coffee table',
 'plastic bag',
 'slot',
 'brown bear',
 'frog',
 'jeans',
 'switchblade',
 'harp',
 'orangutan',
 'accordion',
 'chacma',
 'guenon',
 'pig',
 'porcupine',
 'dolphin',
 'car wheel',
 'owl',
 'dandie dinmont',
 'flowerpot',
 'guanaco',
 'motorcycle',
 'corn',
 'hen',
 'calculator',
 'african hunting dog',
 'tap',
 'kangaroo',
 'pajama',
 'lavender',
 'hay',
 'dingo',
 'tennis ball',
 'meat loaf',
 'kid',
 'jellyfish',
 'whistle',
 'tank car',
 'dungeness crab',
 'bust',
 'dice',
 'pop bottle',
 'wok',
 'roller skates',
 'oar',
 "yellow lady's slipper",
 'mango',
 'mountain sheep',
 'bread',
 'zebu',
 'crossword puzzle',
 'computer monitor',
 'daisy',
 'kimono',
 'sombrero',
 'basenji',
 'desk',
 'solar dish',
 'cheetah',
 'bell',
 'ice cream',
 'gazelle',
 'agaric',
 'tart',
 'doughnut',
 'meatball',
 'grapefruit',
 'patas',
 'paddle',
 'swing',
 'dutch oven',
 'pear',
 'military uniform',
 'vestment',
 'kite',
 'eagle',
 'towel',
 'cavy',
 'coffee',
 'mustang',
 'standard poodle',
 'chesapeake bay retriever',
 'coffee mug',
 'deer',
 'gorilla',
 'bearskin',
 'whale',
 'cello',
 'lion',
 'taxi',
 'safety pin',
 'sulphur crested cockatoo',
 'flamingo',
 'shark',
 'eider',
 'picket fence',
 'human arm',
 'trumpet',
 'french fries',
 'dhole',
 'spaghetti squash',
 'syringe',
 'african elephant',
 'lobster',
 'rose',
 'human hand',
 'coral fungus',
 'pelican',
 'anchovy pear',
 'oystercatcher',
 'lamp',
 'gyromitra',
 'bat',
 'african grey',
 'ostrich',
 'knee pad',
 'trombone',
 'swim cap',
 'human beard',
 'hot dog',
 'chicken',
 'hatchet',
 'leopard',
 'elk',
 'alarm clock',
 'drum',
 'taco',
 'digital clock',
 'squash racket',
 'starfish',
 'train',
 'belt',
 'mallet',
 'refrigerator',
 'greyhound',
 'ram',
 'dog bed',
 'racer',
 'morel',
 'bell pepper',
 'drumstick',
 'loveseat',
 'bovine',
 'bullet train',
 'bernese mountain dog',
 'motor scooter',
 'vervet',
 'quince',
 'blenheim spaniel',
 'infant bed',
 'snipe',
 'training bench',
 'milk',
 'mixing bowl',
 'marmoset',
 'knife',
 'cutting board',
 'ring binder',
 'studio couch',
 'filing cabinet',
 'bee',
 'caterpillar',
 'sofa bed',
 'dodo',
 'cowboy boot',
 'violin',
 'buckeye',
 'prairie chicken',
 'traffic light',
 'airplane',
 'siberian husky',
 'ballpoint',
 'mountain tent',
 'jockey',
 'border collie',
 'ice skate',
 'closet',
 'button',
 'stuffed tomato',
 'lovebird',
 'canary',
 'jinrikisha',
 'toilet paper',
 'canoe',
 'pony',
 'killer whale',
 'spoon',
 'indian elephant',
 'fox',
 'tennis racket',
 'acorn squash',
 'macaw',
 'bolete',
 'fiddler crab',
 'mobile home',
 'dressing table',
 'chimpanzee',
 "jack o' lantern",
 'red panda',
 'toast',
 'cannon',
 'nipple',
 'entlebucher',
 'stool',
 'groom',
 'sarong',
 'cauliflower',
 'apiary',
 'english foxhound',
 'deck chair',
 'car door',
 'zucchini',
 'rugby ball',
 'labrador retriever',
 'wallaby',
 'polar bear',
 'acorn',
 'bench',
 'pizza',
 'short pants',
 'standard schnauzer',
 'lampshade',
 'fork',
 'hog',
 'barge',
 'male horse',
 'bow and arrow',
 'martin',
 'kettle',
 'goldfish',
 'mirror',
 'loudspeaker',
 'snail',
 'poster',
 'drill',
 'tie',
 'plum',
 'bale',
 'partridge',
 'gondola',
 'water jug',
 'scale',
 'shoji',
 'shield',
 'american lobster',
 'falcon',
 'bull',
 'nailfile',
 'poodle',
 'jackfruit',
 'heifer',
 'whippet',
 'remote control',
 'mitten',
 'eggnog',
 'horn',
 'hamster',
 'weimaraner',
 'volleyball',
 'twin bed',
 'english springer',
 'stationary bicycle',
 'dishwasher',
 'dowitcher',
 'rhesus',
 'limousine',
 'norwich terrier',
 'sail',
 'shorts',
 'toothbrush',
 'custard apple',
 'wassail',
 'bib',
 'bookcase',
 'baseball glove',
 'computer mouse',
 'bullet',
 'bartlett',
 'otter',
 'computer keyboard',
 'shower',
 'brace',
 'pick',
 'teapot',
 'carthorse',
 'human foot',
 'parking meter',
 'ruminant',
 'clog',
 'screw',
 'burro',
 'mountain bike',
 'ski',
 'beaker',
 'sunscreen',
 'packet',
 'castle',
 'mobile phone',
 'madagascar cat',
 'suitcase',
 'radio telescope',
 'sock',
 'cupboard',
 'wild sheep',
 'crab',
 'stuffed peppers',
 'okapi',
 'common fig',
 'missile',
 'swimwear',
 'saucer',
 'popcorn',
 'coat',
 'bighorn',
 'plate',
 'grizzly',
 'stairs',
 'pineapple',
 'parrot',
 'fountain',
 'jar',
 'binoculars',
 'rambutan',
 'tent',
 'pencil case',
 'mortarboard',
 'raspberry',
 'gar',
 'andiron',
 'paintbrush',
 'running shoe',
 'turnstile',
 'mouse',
 'leonberg',
 'red wine',
 'sewing machine',
 'open face sandwich',
 'magpie',
 'metal screw',
 'west highland white terrier',
 'handbag',
 'saxophone',
 'panda',
 'flashlight',
 'boxer',
 'lorikeet',
 'interceptor',
 'baseball bat',
 'ruddy turnstone',
 'colobus',
 'golf cart',
 'pan',
 'white stork',
 'banana',
 'billiard table',
 'stinkhorn',
 'american coot',
 'tower',
 'trailer truck',
 'washing machine',
 'bride',
 'afghan hound',
 'motorboat',
 'lizard',
 'bassoon',
 'brassiere',
 'quesadilla',
 'goblet',
 'llama',
 'folding chair',
 'spoonbill',
 'ant',
 'workhorse',
 'crown',
 'pimento',
 'anemone fish',
 'oven',
 'sea lion',
 'ewe',
 'pitcher',
 'megalith',
 'pool ball',
 'chest of drawers',
 'macaque',
 'kit fox',
 'oryx',
 'sleeve',
 'crutch',
 'plug',
 'battery',
 'black stork',
 'hippopotamus',
 'saluki',
 'bath towel',
 'artichoke',
 'seat belt',
 'bee eater',
 'baboon',
 'dairy cattle',
 'sleeping bag',
 'panpipe',
 'gemsbok',
 'microphone',
 'lynx',
 'camel',
 'rabbit',
 'rocket',
 'toilet',
 'albatross',
 'spider',
 'comb',
 'snow goose',
 'cetacean',
 'camera',
 'bucket',
 'packhorse',
 'palm',
 'vending machine',
 'butternut squash',
 'loupe',
 'ox',
 'celandine',
 'appenzeller',
 'pomegranate',
 'bathtub',
 'vulture',
 'crampon',
 'jug',
 'backboard',
 'european gallinule',
 'goat',
 'cowboy hat',
 'parsnip',
 'jersey',
 'slide',
 'guava',
 'wrench',
 'cardoon',
 'scuba diver',
 'broom',
 'giant schnauzer',
 'stretcher',
 'balance beam',
 'gordon setter',
 'necklace',
 'scoreboard',
 'horizontal bar',
 'stop sign',
 'sushi',
 'staffordshire bullterrier',
 'gas stove',
 'conch',
 'cherry',
 'jam',
 'salmon',
 'matchstick',
 'tank',
 'armadillo',
 'black swan',
 'sailboat',
 'assault rifle',
 'snake',
 'thatch',
 'tripod',
 'hook',
 'wild boar',
 'cocktail',
 'ski pole',
 'zebra',
 'toaster',
 'armchair',
 'lab coat',
 'goldfinch',
 'guinea pig',
 'frying pan',
 'pinwheel',
 'water buffalo',
 'pasta',
 'chain',
 'ocarina',
 'impala',
 'swallow',
 'mailbox',
 'langur',
 'cock',
 'hyena',
 'marimba',
 'hound',
 'truck',
 'blue jay',
 'knot',
 'saw',
 'eskimo dog',
 'pembroke',
 'sink',
 'lighthouse',
 'skateboard',
 'sealyham terrier',
 'cricket ball',
 'dragonfly',
 'snowplow',
 'italian greyhound',
 'shih tzu',
 'scotch terrier',
 'yawl',
 'screwdriver',
 'organ',
 'lighter',
 'giraffe',
 'submarine',
 'dung beetle',
 'scorpion',
 'dugong',
 'academic gown',
 'blanket',
 'honeycomb',
 'timber wolf',
 'cream',
 'minibus',
 'joystick',
 'cart',
 'koala',
 'speedboat',
 'guacamole',
 'flagpole',
 'raven',
 'drawer',
 'honey',
 'diaper',
 'chessman',
 'fire hydrant',
 'club sandwich',
 'potato',
 'porch',
 'banjo',
 'gown',
 'crate',
 'peg',
 'hammer',
 'aquarium',
 'whooping crane',
 'headboard',
 'okra',
 'trench coat',
 'avocado',
 'cayuse',
 'paper towel',
 "large yellow lady's slipper",
 'ski mask',
 'dough',
 'bassarisk',
 'bridal gown',
 'wardrobe',
 'terrapin',
 'yacht',
 'soap dispenser',
 'saddle',
 'redbone',
 'asparagus',
 'skunk',
 'chainsaw',
 'shower curtain',
 'jennet',
 'spatula',
 'ambulance',
 'school bus',
 'otterhound',
 'irish terrier',
 'carton',
 'abaya',
 'submarine sandwich',
 'axe',
 'ruler',
 'window shade',
 'measuring cup',
 'wooden spoon',
 'yurt',
 'scarf',
 'squirrel',
 'flat coated retriever',
 'bull mastiff',
 'cardigan',
 'river boat',
 'irish wolfhound',
 'oxygen mask',
 'propeller',
 'earthstar',
 'black footed ferret',
 'tea',
 'rocking chair',
 'whisk',
 'food processor',
 'beach wagon',
 'litchi',
 'pigeon',
 'tick',
 'stapler',
 'oboe']
fsod_novel_classes = ['beer',
 'musical keyboard',
 'jalapeno',
 'maple',
 'cartwheel',
 'christmas tree',
 'hiking equipment',
 'bicycle helmet',
 'laelia',
 'cattleya',
 'bran muffin',
 'goggles',
 'caribou',
 'buskin',
 'turban',
 'tortoise',
 'whiteboard',
 'chalk',
 'cider vinegar',
 'lantern',
 'bannock',
 'convenience store',
 'persimmon',
 'lifejacket',
 'squid',
 'watermelon',
 'wing tip',
 'sunflower',
 'shin guard',
 'baby shoe',
 'muffin',
 'mixer',
 'bronze sculpture',
 'euphonium',
 'skyscraper',
 'drinking straw',
 'popover',
 'segway',
 'sun hat',
 'harbor seal',
 'cat furniture',
 'fedora',
 'kitchen knife',
 'pulley',
 'walking shoe',
 'fancy dress',
 'clam',
 'hand dryer',
 'mozzarella',
 'peccary',
 'spinning rod',
 'tree house',
 'khimar',
 'earrings',
 'power plugs and sockets',
 'waste container',
 'blender',
 'briefcase',
 'soap dish',
 'hot air balloon',
 'windmill',
 'street light',
 'shotgun',
 'sports uniform',
 'manometer',
 'wood burning stove',
 'gnu',
 'earphone',
 'double hung window',
 'billboard',
 'conserve',
 'claymore',
 'vehicle registration plate',
 'ceiling fan',
 'cassette deck',
 'table tennis racket',
 'scone',
 'bouquet',
 'bidet',
 'ski boot',
 'pumpkin',
 'welsh poppy',
 'tablet computer',
 'rhinoceros',
 'cheese',
 'jacuzzi',
 'door handle',
 'puffball',
 'swimming pool',
 'rays and skates',
 'chopsticks',
 'oyster',
 'office building',
 'ratchet',
 'sambuca',
 'truffle',
 'salt and pepper shakers',
 'calla lily',
 'hard hat',
 'elephant seal',
 'peanut',
 'hind',
 'jelly fungus',
 'juice',
 'pirogi',
 'bowling equipment',
 'recycling bin',
 'skull',
 'nightstand',
 'light bulb',
 'high heels',
 'picnic basket',
 'in line skate',
 'platter',
 'bialy',
 'shelf bracket',
 'cantaloupe',
 'croissant',
 'bowling shoe',
 'ferris wheel',
 'dinosaur',
 'adhesive tape',
 'stanhopea',
 'mechanical fan',
 'winter melon',
 'cowrie',
 'adjustable wrench',
 'date bread',
 'o ring',
 'caryatid',
 'egg',
 'beehive',
 'lily',
 'leaf spring',
 'french bread',
 'cake stand',
 'sergeant major',
 'treadmill',
 'daiquiri',
 'sweet roll',
 'polypore',
 'face veil',
 'kitchen & dining room table',
 'support hose',
 'headphones',
 'chinese lantern',
 'wine rack',
 'triangle',
 'mulberry',
 'quick bread',
 'harpsichord',
 'optical disk',
 'egg yolk',
 'shallot',
 'strawflower',
 'cue',
 'corded phone',
 'blue columbine',
 'silo',
 'mascara',
 'snowman',
 'cherry tomato',
 'box wrench',
 'flipper',
 'jet ski',
 'bathrobe',
 'fireplace',
 'gill fungus',
 'blackboard',
 'thumbtack',
 'spice rack',
 'longhorn',
 'pacific walrus',
 'streptocarpus',
 'coconut',
 'addax',
 'coffeemaker',
 'fly orchid',
 'blackberry',
 'kob',
 'car tire',
 'seahorse',
 'tiara',
 'sassaby',
 'fishing rod',
 'baguet',
 'trowel',
 'light switch',
 'cornbread',
 'disa',
 'serving tray',
 'tuning fork',
 'virginia spring beauty',
 'samosa',
 'bathroom cabinet',
 'chigetai',
 'blue poppy',
 'scimitar',
 'shirt button',
 'slow cooker']

fsvod_base_classes = ['airplane',
 'airplane_drone',
 'alaskan_brown_bear',
 'albatross',
 'alpaca',
 'ambulance',
 'american_bison',
 'angora_cat',
 'appaloosa',
 'armchair',
 'asiatic_black_bear',
 'australian_blacksnake',
 'backpack',
 'bald_eagle',
 'banded_gecko',
 'banded_sand_snake',
 'barge',
 'baseball_bat',
 'basket',
 'basketball',
 'beaker',
 'bear',
 'bear_cub',
 'bed',
 'bee',
 'beetle',
 'bernese_mountain_dog',
 'bettong',
 'bicycle',
 'big_truck',
 'binder',
 'biscuit_(bread)',
 'black-crowned_night_heron',
 'black-necked_cobra',
 'black_gecko',
 'black_stork',
 'black_vulture',
 'blanket',
 'blindworm_blindworm',
 'blue_point_siamese',
 'boa',
 'boneshaker',
 'book',
 'booklet',
 'border_collie',
 'border_terrier',
 'bottle',
 'bovine',
 'bowl',
 'brambling',
 'briefcase',
 'brig',
 'brigantine',
 'broom',
 'brougham',
 'brush',
 'brush-tailed_porcupine',
 'bull',
 'bulldozer',
 'bumboat',
 'bumper_car',
 'burmese_cat',
 'bus_(vehicle)',
 'buzzard',
 'can',
 'canal_boat',
 'candle',
 'canister',
 'canoeing',
 'cape_buffalo',
 'capybara',
 'carabao',
 'cargo_ship',
 'carton',
 'cat',
 'cellular_telephone',
 'chair',
 'chameleon',
 'cheviot',
 'cinnamon_bear',
 'cockroach',
 'common_kingsnake',
 'common_starling',
 'computer_keyboard',
 'condor',
 'convertible',
 'cornet',
 'cotswold',
 'coupe',
 'cow',
 'coypu',
 'crow',
 'cryptoprocta',
 'cup',
 'curassow',
 'cutter',
 'cutting_tool',
 'dall_sheep',
 'dhow',
 'dirt_bike',
 'dispenser',
 'dog',
 'domestic_llama',
 'dove',
 'dress_hat',
 'drone',
 'duck',
 'dune_buggy',
 'egyptian_cat',
 'electric_locomotive',
 'elephant',
 'fan',
 'faucet',
 'fire_engine',
 'fireboat',
 'flamingo',
 'football',
 'forklift',
 'frilled_lizard',
 'frog',
 'gift_wrap',
 'gila_monster',
 'giraffe',
 'glider',
 'gnu',
 'go-kart',
 'golfcart',
 'goose',
 'gopher',
 'green_lizard',
 'grizzly',
 'grocery_bag',
 'grouse',
 'hagfish',
 'hair_dryer',
 'handbag',
 'hat',
 'hedge_sparrow',
 'helmet',
 'heron',
 'hinny',
 'hockey_stick',
 'horse',
 'horseless_carriage',
 'hyrax',
 'iceboat',
 'icebreaker',
 'ichneumon',
 'indian_cobra',
 'indian_mongoose',
 'indian_rat_snake',
 'interceptor',
 'irish_terrier',
 'irish_wolfhound',
 'jacket',
 'jeep',
 'kanchil',
 'kayak',
 'kinkajou',
 'kite',
 'kitty',
 'knife',
 'ladle',
 'lamp',
 'landing_craft',
 'laptop_computer',
 'lawn_mower',
 'lerot',
 'lippizan',
 'lizard',
 'lovebird',
 'lugger',
 'magpie',
 'mailboat',
 'manx',
 'marco_polo_sheep',
 'marine_iguana',
 'marker',
 'merino',
 'microphone',
 'minicab',
 'minivan',
 'mole',
 'moloch',
 'money',
 'monitor_(computer_equipment) computer_monitor',
 'morgan',
 'moth',
 'motor_scooter',
 'motorboat',
 'motorcycle',
 'mountain_beaver',
 'mountain_bike',
 'musk_ox',
 'napkin',
 'night_snake',
 'notebook',
 'orthopter',
 'otter_shrew',
 'otterhound',
 'owl',
 'packet',
 'paddle',
 'paintbrush',
 'palomino',
 'paper_towel',
 'passenger_boat',
 'patrol_boat',
 'peacock',
 'pekinese',
 'pelican',
 'pen',
 'penguin',
 'pheasant',
 'pickup_truck',
 'pillow',
 'pine_snake',
 'pink_cockatoo',
 'pinto',
 'pitcher_(vessel_for_liquid)',
 'plate',
 'plodder',
 'plover',
 'polar_bear',
 'pole_horse',
 'pony',
 'pot',
 'praying_mantis',
 "przewalski's_horse",
 'pt_boat',
 'punt',
 'push-bike',
 'pygmy_mouse',
 'quarter_horse',
 'racerunner',
 'racket',
 'rat',
 'raven',
 'reconnaissance_plane',
 'recreational_fishing_boat',
 'refrigerator',
 'remote_control',
 'rhodesian_ridgeback',
 'road_race',
 'rock_hyrax',
 'roller_coaster',
 'sailboard',
 'sailboat',
 'sandwich',
 'scissors',
 'scooter',
 'scorpion',
 'scotch_terrier',
 'sealyham_terrier',
 'sheep',
 'skateboard',
 'skidder',
 'sloth_bear',
 'small_boat',
 'small_motorcycle',
 'snail',
 'snowplow',
 'sofa',
 'space_shuttle',
 'spider',
 'spoon',
 'sport_utility',
 'spotted_gecko',
 'standard_poodle',
 'standard_schnauzer',
 'stanley_steamer',
 'stealth_bomber',
 'stealth_fighter',
 'steamboat',
 'steamroller',
 'subcompact',
 'sunglasses',
 'surfboard',
 'sweater',
 'tabby',
 'takin',
 'tape_(sticky_cloth_or_paper)',
 'tasmanian_devil',
 'teacup',
 'teapot',
 'telephone',
 'texas_horned_lizard',
 'tiger_cat',
 'tissue_paper',
 'toast_(food)',
 'toothbrush',
 'toothpaste',
 'tortoiseshell',
 'towel',
 'traffic_sign',
 'train',
 'tramcar',
 'trawler',
 'tree_lizard',
 'tree_shrew',
 'trolleybus',
 'truck',
 'umbrella',
 'vacuum_cleaner',
 'viscacha',
 'volleyball',
 'water-drop',
 'water_cart',
 'water_wagon',
 'white_stork',
 'whitetail_prairie_dog',
 'wildcat',
 'wineglass',
 'wisent',
 'wolverine',
 'wombat',
 'woodlouse',
 'worm_lizard',
 'yellow_gecko',
 'zebra']

fsvod_novel_classes = ['JetLev-Flyer',
 'amphibian',
 'aoudad',
 'asian_crocodile',
 'autogiro',
 'ax',
 'bactrian_camel',
 'balloon',
 'bathyscaphe',
 'belgian_hare',
 'binturong',
 'black_rabbit',
 'black_squirrel',
 'bow_(weapon)',
 'brahman',
 'canada_porcupine',
 'cheetah',
 'chiacoan_peccary',
 'chimaera',
 'chinese_paddlefish',
 'coin',
 'crab',
 'crayfish',
 'cruise_missile',
 'deer',
 'destroyer_escort',
 'dumpcart',
 'elasmobranch',
 'elk',
 'fall_cankerworm',
 'fanaloka',
 'fish',
 'flag',
 'fox',
 'garden_centipede',
 'gavial',
 'gemsbok',
 'giant_panda',
 'goat',
 'guard_ship',
 'guitar',
 'hand_truck',
 'hermit_crab',
 'hog',
 'horse_cart',
 'horseshoe_crab',
 'humvee',
 'ibex',
 'indian_rhinoceros',
 'lander',
 'langur',
 'lappet_caterpillar',
 'lemur',
 'leopard',
 'lesser_panda',
 'lion',
 'luge',
 'malayan_tapir',
 'minisub',
 'monkey',
 'mouflon',
 'mountain_goat',
 'orangutan',
 'pacific_walrus',
 'peba',
 'pedicab',
 'peludo',
 "pere_david's_deer",
 'pistol',
 'pony_cart',
 'pung',
 'rabbit',
 'raccoon',
 'reconnaissance_vehicle',
 'rubic_cube',
 'sassaby',
 'saxophone',
 'sepia',
 'serow',
 'shark',
 'shawl',
 'skibob',
 'snow_leopard',
 'snowmobil',
 'sow',
 'spider_monkey',
 'squirrel',
 'suricate',
 'tadpole_shrimp',
 'tiglon',
 'virginia_deer',
 'warthog',
 'whale',
 'wheelchair',
 'white-tailed_jackrabbit',
 'white_crocodile',
 'white_rabbit',
 'white_rhinoceros',
 'white_squirrel',
 'woolly_monkey']

# from fs_coco_test_all
fs_coco_2014_all_classes = MetadataCatalog.get('coco_2014_val').thing_classes

def get_oneshot_split(split):
    return [coco17_all_classes[cid] for cid in range(80) if contiguous_id_to_thing_dataset_id[cid] % 4 != split]

voc_split1_base = [
        "aeroplane",
        "bicycle",
        "boat",
        "bottle",
        "car",
        "cat",
        "chair",
        "diningtable",
        "dog",
        "horse",
        "person",
        "pottedplant",
        "sheep",
        "train",
        "tvmonitor",
    ]

voc_split2_base = [
        "bicycle",
        "bird",
        "boat",
        "bus",
        "car",
        "cat",
        "chair",
        "diningtable",
        "dog",
        "motorbike",
        "person",
        "pottedplant",
        "sheep",
        "train",
        "tvmonitor",
    ]

voc_split3_base = [
        "aeroplane",
        "bicycle",
        "bird",
        "bottle",
        "bus",
        "car",
        "chair",
        "cow",
        "diningtable",
        "dog",
        "horse",
        "person",
        "pottedplant",
        "train",
        "tvmonitor",
    ]

voc_split1_all = [
        "aeroplane",
        "bicycle",
        "boat",
        "bottle",
        "car",
        "cat",
        "chair",
        "diningtable",
        "dog",
        "horse",
        "person",
        "pottedplant",
        "sheep",
        "train",
        "tvmonitor",
        "bird",
        "bus",
        "cow",
        "motorbike",
        "sofa",
    ]

voc_split2_all = [
        "bicycle",
        "bird",
        "boat",
        "bus",
        "car",
        "cat",
        "chair",
        "diningtable",
        "dog",
        "motorbike",
        "person",
        "pottedplant",
        "sheep",
        "train",
        "tvmonitor",
        "aeroplane",
        "bottle",
        "cow",
        "horse",
        "sofa",
    ]

voc_split3_all = [
        "aeroplane",
        "bicycle",
        "bird",
        "bottle",
        "bus",
        "car",
        "chair",
        "cow",
        "diningtable",
        "dog",
        "horse",
        "person",
        "pottedplant",
        "train",
        "tvmonitor",
        "boat",
        "cat",
        "motorbike",
        "sheep",
        "sofa",
    ]

SEEN_CLS_DICT = {
    COCO_OVD: COCO_SEEN_CLS,
    LVIS: ['aerosol_can', 'air_conditioner', 'airplane', 'alarm_clock', 'alcohol', 'alligator', 'almond', 'ambulance', 'amplifier', 'anklet', 'antenna', 'apple', 'apron', 'aquarium', 'armband', 'armchair', 'artichoke', 'trash_can', 'ashtray', 'asparagus', 'atomizer', 'avocado', 'award', 'awning', 'baby_buggy', 'basketball_backboard', 'backpack', 'handbag', 'suitcase', 'bagel', 'ball', 'balloon', 'bamboo', 'banana', 'Band_Aid', 'bandage', 'bandanna', 'banner', 'barrel', 'barrette', 'barrow', 'baseball_base', 'baseball', 'baseball_bat', 'baseball_cap', 'baseball_glove', 'basket', 'basketball', 'bat_(animal)', 'bath_mat', 'bath_towel', 'bathrobe', 'bathtub', 'battery', 'bead', 'bean_curd', 'beanbag', 'beanie', 'bear', 'bed', 'bedspread', 'cow', 'beef_(food)', 'beer_bottle', 'beer_can', 'bell', 'bell_pepper', 'belt', 'belt_buckle', 'bench', 'beret', 'bib', 'bicycle', 'visor', 'billboard', 'binder', 'binoculars', 'bird', 'birdfeeder', 'birdbath', 'birdcage', 'birdhouse', 'birthday_cake', 'black_sheep', 'blackberry', 'blackboard', 'blanket', 'blazer', 'blender', 'blinker', 'blouse', 'blueberry', 'boat', 'bobbin', 'bobby_pin', 'boiled_egg', 'deadbolt', 'bolt', 'book', 'bookcase', 'booklet', 'boot', 'bottle', 'bottle_opener', 'bouquet', 'bow_(decorative_ribbons)', 'bow-tie', 'bowl', 'bowler_hat', 'box', 'suspenders', 'bracelet', 'brassiere', 'bread-bin', 'bread', 'bridal_gown', 'briefcase', 'broccoli', 'broom', 'brownie', 'brussels_sprouts', 'bucket', 'horned_cow', 'bulldog', 'bullet_train', 'bulletin_board', 'bullhorn', 'bun', 'bunk_bed', 'buoy', 'bus_(vehicle)', 'business_card', 'butter', 'butterfly', 'button', 'cab_(taxi)', 'cabin_car', 'cabinet', 'cake', 'calculator', 'calendar', 'calf', 'camcorder', 'camel', 'camera', 'camera_lens', 'camper_(vehicle)', 'can', 'can_opener', 'candle', 'candle_holder', 'candy_cane', 'walking_cane', 'canister', 'canoe', 'cantaloup', 'cap_(headwear)', 'bottle_cap', 'cape', 'cappuccino', 'car_(automobile)', 'railcar_(part_of_a_train)', 'identity_card', 'card', 'cardigan', 'horse_carriage', 'carrot', 'tote_bag', 'cart', 'carton', 'cash_register', 'cast', 'cat', 'cauliflower', 'cayenne_(spice)', 'CD_player', 'celery', 'cellular_telephone', 'chair', 'chandelier', 'cherry', 'chicken_(animal)', 'chickpea', 'chili_(vegetable)', 'crisp_(potato_chip)', 'chocolate_bar', 'chocolate_cake', 'choker', 'chopping_board', 'chopstick', 'Christmas_tree', 'slide', 'cigarette', 'cigarette_case', 'cistern', 'clasp', 'cleansing_agent', 'clip', 'clipboard', 'clock', 'clock_tower', 'clothes_hamper', 'clothespin', 'coaster', 'coat', 'coat_hanger', 'coatrack', 'cock', 'coconut', 'coffee_maker', 'coffee_table', 'coffeepot', 'coin', 'colander', 'coleslaw', 'pacifier', 'computer_keyboard', 'condiment', 'cone', 'control', 'cookie', 'cooler_(for_food)', 'cork_(bottle_plug)', 'corkscrew', 'edible_corn', 'cornet', 'cornice', 'corset', 'costume', 'cowbell', 'cowboy_hat', 'crab_(animal)', 'cracker', 'crate', 'crayon', 'crescent_roll', 'crib', 'crock_pot', 'crossbar', 'crow', 'crown', 'crucifix', 'cruise_ship', 'police_cruiser', 'crumb', 'crutch', 'cub_(animal)', 'cube', 'cucumber', 'cufflink', 'cup', 'trophy_cup', 'cupboard', 'cupcake', 'curtain', 'cushion', 'dartboard', 'deck_chair', 'deer', 'dental_floss', 'desk', 'diaper', 'dining_table', 'dish', 
            'dish_antenna', 'dishrag', 'dishtowel', 'dishwasher', 'dispenser', 'Dixie_cup', 'dog', 'dog_collar', 'doll', 'dolphin', 'domestic_ass', 'doorknob', 'doormat', 'doughnut', 'drawer', 'underdrawers', 'dress', 'dress_hat', 'dress_suit', 'dresser', 'drill', 'drum_(musical_instrument)', 'duck', 'duckling', 'duct_tape', 'duffel_bag', 'dumpster', 'eagle', 'earphone', 'earring', 'easel', 'egg', 'egg_yolk', 'eggbeater', 'eggplant', 'refrigerator', 'elephant', 'elk', 'envelope', 'eraser', 'fan', 'faucet', 'Ferris_wheel', 'ferry', 'fighter_jet', 'figurine', 'file_cabinet', 'fire_alarm', 'fire_engine', 'fire_extinguisher', 'fire_hose', 'fireplace', 'fireplug', 'fish', 'fish_(food)', 'fishing_rod', 'flag', 'flagpole', 'flamingo', 'flannel', 'flap', 'flashlight', 'flip-flop_(sandal)', 'flipper_(footwear)', 'flower_arrangement', 'flute_glass', 'foal', 'folding_chair', 'food_processor', 'football_(American)', 'footstool', 'fork', 'forklift', 'freight_car', 'French_toast', 'freshener', 'frisbee', 'frog', 'fruit_juice', 'frying_pan', 'garbage_truck', 'garden_hose', 'gargle', 'garlic', 'gazelle', 'gelatin', 'giant_panda', 'gift_wrap', 'ginger', 'giraffe', 'cincture', 'glass_(drink_container)', 'globe', 'glove', 'goat', 'goggles', 'golf_club', 'golfcart', 'goose', 'grape', 'grater', 'gravestone', 'green_bean', 'green_onion', 'grill', 'grizzly', 'grocery_bag', 'guitar', 'gull', 'gun', 'hairbrush', 'hairnet', 'hairpin', 'ham', 'hamburger', 'hammer', 'hammock', 'hamster', 'hair_dryer', 'hand_towel', 'handcart', 'handkerchief', 'handle', 'hat', 'veil', 'headband', 'headboard', 'headlight', 'headscarf', 'headstall_(for_horses)', 'heart', 'heater', 'helicopter', 'helmet', 'highchair', 'hinge', 'hog', 'home_plate_(baseball)', 'honey', 'fume_hood', 'hook', 'horse', 'hose', 'hot_sauce', 'hummingbird', 'polar_bear', 'icecream', 'ice_maker', 'igniter', 'iPod', 'iron_(for_clothing)', 'ironing_board', 'jacket', 'jam', 'jar', 'jean', 'jeep', 'jersey', 'jet_plane', 'jewelry', 'jumpsuit', 'kayak', 'kettle', 'key', 'kilt', 'kimono', 'kitchen_sink', 'kite', 'kitten', 'kiwi_fruit', 'knee_pad', 'knife', 'knob', 'ladder', 'ladle', 'ladybug', 'lamb_(animal)', 'lamp', 'lamppost', 'lampshade', 'lantern', 'lanyard', 'laptop_computer', 'latch', 'legging_(clothing)', 'Lego', 'lemon', 'lettuce', 'license_plate', 'life_buoy', 'life_jacket', 'lightbulb', 'lime', 'lion', 'lip_balm', 'lizard', 'log', 'lollipop', 'speaker_(stero_equipment)', 'loveseat', 'magazine', 'magnet', 'mail_slot', 'mailbox_(at_home)', 'mandarin_orange', 'manger', 'manhole', 'map', 'marker', 'mashed_potato', 'mask', 'mast', 'mat_(gym_equipment)', 'mattress', 'measuring_cup', 'measuring_stick', 'meatball', 'medicine', 'melon', 'microphone', 'microwave_oven', 'milk', 'minivan', 'mirror', 'mitten', 'mixer_(kitchen_tool)', 'money', 'monitor_(computer_equipment) computer_monitor', 'monkey', 'motor', 'motor_scooter', 'motorcycle', 'mound_(baseball)', 'mouse_(computer_equipment)', 'mousepad', 'muffin', 'mug', 'mushroom', 'musical_instrument', 'napkin', 'necklace', 'necktie', 'needle', 'nest', 'newspaper', 'newsstand', 'nightshirt', 'noseband_(for_animals)', 'notebook', 'notepad', 'nut', 'oar', 'oil_lamp', 'olive_oil', 'onion', 'orange_(fruit)', 'orange_juice', 'ostrich', 'ottoman', 'oven', 'overalls_(clothing)', 'owl', 'packet', 'pad', 'paddle', 'padlock', 'paintbrush', 'painting', 'pajamas', 'palette', 'pan_(for_cooking)', 'pancake', 'paper_plate', 'paper_towel', 'parachute', 'parakeet', 'parasail_(sports)', 'parasol', 'parka', 'parking_meter', 'parrot', 'passenger_car_(part_of_a_train)', 'passport', 'pastry', 'pea_(food)', 'peach', 'peanut_butter', 'pear', 'peeler_(tool_for_fruit_and_vegetables)', 'pelican', 'pen', 'pencil', 'penguin', 'pepper', 'pepper_mill', 'perfume', 'person', 'pet', 'pew_(church_bench)', 'phonograph_record', 'piano', 'pickle', 'pickup_truck', 'pie', 'pigeon', 'pillow', 'pineapple', 'pinecone', 'pipe', 'pita_(bread)', 'pitcher_(vessel_for_liquid)', 'pizza', 'place_mat', 'plate', 'platter', 'pliers', 'pocketknife', 'poker_(fire_stirring_tool)', 'pole', 'polo_shirt', 'pony', 'pop_(soda)', 'postbox_(public)', 'postcard', 'poster', 'pot', 'flowerpot', 'potato', 'potholder', 'pottery', 'pouch', 'power_shovel', 'prawn', 'pretzel', 'printer', 'projectile_(weapon)', 'projector', 'propeller', 'pumpkin', 'puppy', 'quilt', 'rabbit', 'racket', 'radiator', 'radio_receiver', 'radish', 'raft', 'raincoat', 'ram_(animal)', 'raspberry', 'razorblade', 'reamer_(juicer)', 'rearview_mirror', 'receipt', 'recliner', 'record_player', 'reflector', 'remote_control', 'rhinoceros', 'rifle', 'ring', 'robe', 'rocking_chair', 'rolling_pin', 'router_(computer_equipment)', 'rubber_band', 'runner_(carpet)', 'plastic_bag', 'saddle_(on_an_animal)', 'saddle_blanket', 'saddlebag', 'sail', 'salad', 'salami', 'salmon_(fish)', 'salsa', 'saltshaker', 'sandal_(type_of_shoe)', 'sandwich', 'saucer', 'sausage', 'scale_(measuring_instrument)', 'scarf', 'school_bus', 'scissors', 'scoreboard', 'screwdriver', 'scrubbing_brush', 'sculpture', 'seabird', 'seahorse', 'seashell', 'sewing_machine', 'shaker', 'shampoo', 'shark', 'shaving_cream', 'sheep', 'shield', 'shirt', 'shoe', 'shopping_bag', 'shopping_cart', 'short_pants', 'shoulder_bag', 'shovel', 'shower_head', 'shower_curtain', 'signboard', 'silo', 'sink', 'skateboard', 'skewer', 'ski', 'ski_boot', 'ski_parka', 'ski_pole', 'skirt', 'sled', 'sleeping_bag', 'slipper_(footwear)', 'snowboard', 'snowman', 'snowmobile', 'soap', 'soccer_ball', 'sock', 'sofa', 'solar_array', 'soup', 'soupspoon', 'sour_cream', 'spatula', 'spectacles', 'spice_rack', 'spider', 'sponge', 'spoon', 'sportswear', 'spotlight', 'squirrel', 'stapler_(stapling_machine)', 'starfish', 'statue_(sculpture)', 'steak_(food)', 'steering_wheel', 'step_stool', 'stereo_(sound_system)', 'stirrup', 'stool', 'stop_sign', 'brake_light', 'stove', 'strainer', 'strap', 'straw_(for_drinking)', 'strawberry', 'street_sign', 'streetlight', 'suit_(clothing)', 'sunflower', 'sunglasses', 'sunhat', 'surfboard', 'sushi', 'mop', 'sweat_pants', 'sweatband', 'sweater', 'sweatshirt', 'sweet_potato', 'swimsuit', 'sword', 'table', 'table_lamp', 'tablecloth', 'tag', 'taillight', 'tank_(storage_vessel)', 'tank_top_(clothing)', 'tape_(sticky_cloth_or_paper)', 'tape_measure', 'tapestry', 'tarp', 'tartan', 'tassel', 'tea_bag', 'teacup', 'teakettle', 'teapot', 'teddy_bear', 'telephone', 'telephone_booth', 'telephone_pole', 'television_camera', 'television_set', 'tennis_ball', 'tennis_racket', 'thermometer', 'thermos_bottle', 'thermostat', 'thread', 'thumbtack', 'tiara', 'tiger', 'tights_(clothing)', 'timer', 'tinfoil', 'tinsel', 'tissue_paper', 'toast_(food)', 'toaster', 'toaster_oven', 'toilet', 'toilet_tissue', 'tomato', 'tongs', 'toolbox', 'toothbrush', 'toothpaste', 'toothpick', 'cover', 'tortilla', 'tow_truck', 'towel', 'towel_rack', 'toy', 'tractor_(farm_equipment)', 'traffic_light', 'dirt_bike', 'trailer_truck', 'train_(railroad_vehicle)', 'tray', 'tricycle', 'tripod', 'trousers', 'truck', 'trunk', 'turban', 'turkey_(food)', 'turtle', 'turtleneck_(clothing)', 'typewriter', 'umbrella', 'underwear', 'urinal', 'urn', 'vacuum_cleaner', 'vase', 'vending_machine', 'vent', 'vest', 'videotape', 'volleyball', 'waffle', 'wagon', 'wagon_wheel', 'walking_stick', 'wall_clock', 'wall_socket', 'wallet', 'automatic_washer', 'watch', 'water_bottle', 'water_cooler', 'water_faucet', 'water_jug', 'water_scooter', 'water_ski', 'water_tower', 'watering_can', 'watermelon', 'weathervane', 'webcam', 'wedding_cake', 'wedding_ring', 'wet_suit', 'wheel', 'wheelchair', 'whipped_cream', 'whistle', 'wig', 'wind_chime', 'windmill', 'window_box_(for_plants)', 'windshield_wiper', 'windsock', 'wine_bottle', 'wine_bucket', 'wineglass', 'blinder_(for_horses)', 'wok', 'wooden_spoon', 'wreath', 'wrench', 'wristband', 'wristlet', 'yacht', 'yogurt', 'yoke_(animal_equipment)', 'zebra', 'zucchini'],
    LVIS_FEW: MetadataCatalog.get('lvis_v1_few').thing_classes,

    COCO_2017_SPLIT_1: get_oneshot_split(1),
    COCO_2017_SPLIT_2: get_oneshot_split(2),
    COCO_2017_SPLIT_3: get_oneshot_split(3),
    COCO_2017_SPLIT_4: get_oneshot_split(0),

    COCO_2014_FEW_SHOT: fs_coco_2014_seen_classes,
    COCO_2017_FEW_SHOT: fs_coco_2014_seen_classes,
    
    COCO_2014_FEW_TEN_SHOT: fs_coco_2014_all_classes,
    COCO_2014_FEW_THIRTY_SHOT: fs_coco_2014_all_classes,
    
    FSOD1K_BASE: fsod_base_classes,
    FSOD1K_5SHOT: fsod_novel_classes,
    FSOD1K_TEST: fsod_novel_classes,
    FSVOD_TEST_ALL: fsod_novel_classes,
    
    FSVOD_BASE: fsvod_base_classes,
    FSVOD_5SHOT: fsvod_novel_classes,
    FSVOD_TEST: fsvod_novel_classes,
    
    VOC_BASE1: voc_split1_base,
    VOC_BASE2: voc_split2_base,
    VOC_BASE3: voc_split3_base,
    
    VOC_TEST1: voc_split1_base,
    VOC_TEST2: voc_split2_base,
    VOC_TEST3: voc_split3_base,
    
    VOC_SPLIT1_1: voc_split1_all,
    VOC_SPLIT1_2: voc_split1_all,
    VOC_SPLIT1_3: voc_split1_all,
    VOC_SPLIT1_5: voc_split1_all,
    VOC_SPLIT1_10: voc_split1_all,
    
    VOC_SPLIT2_1: voc_split2_all,
    VOC_SPLIT2_2: voc_split2_all,
    VOC_SPLIT2_3: voc_split2_all,
    VOC_SPLIT2_5: voc_split2_all,
    VOC_SPLIT2_10: voc_split2_all,
    
    VOC_SPLIT3_1: voc_split3_all,
    VOC_SPLIT3_2: voc_split3_all,
    VOC_SPLIT3_3: voc_split3_all,
    VOC_SPLIT3_5: voc_split3_all,
    VOC_SPLIT3_10: voc_split3_all,
}


ALL_CLS_DICT = {
    COCO_OVD: COCO_OVD_ALL_CLS,
    LVIS: MetadataCatalog.get('lvis_v1_train').thing_classes,
    LVIS_FEW: MetadataCatalog.get('lvis_v1_few').thing_classes,

    COCO_2017_SPLIT_1: coco17_all_classes,
    COCO_2017_SPLIT_2: coco17_all_classes,
    COCO_2017_SPLIT_3: coco17_all_classes,
    COCO_2017_SPLIT_4: coco17_all_classes,
    
    COCO_2014_FEW_SHOT: fs_coco_2014_all_classes,
    COCO_2017_FEW_SHOT: fs_coco_2014_all_classes,
    
    COCO_2014_FEW_TEN_SHOT: fs_coco_2014_all_classes,
    COCO_2014_FEW_THIRTY_SHOT: fs_coco_2014_all_classes,
    
    FSOD1K_BASE: fsod_base_classes+fsod_novel_classes,
    FSOD1K_5SHOT: fsod_novel_classes,
    FSOD1K_TEST: fsod_novel_classes,
    FSVOD_TEST_ALL: fsod_novel_classes,
    
    FSVOD_BASE: fsvod_base_classes+fsvod_novel_classes,
    FSVOD_5SHOT: fsvod_novel_classes,
    FSVOD_TEST: fsvod_novel_classes,
    
    VOC_BASE1: voc_split1_all,
    VOC_BASE2: voc_split2_all,
    VOC_BASE3: voc_split3_all,
    
    VOC_TEST1: voc_split1_all,
    VOC_TEST2: voc_split2_all,
    VOC_TEST3: voc_split3_all,
    
    VOC_SPLIT1_1: voc_split1_all,
    VOC_SPLIT1_2: voc_split1_all,
    VOC_SPLIT1_3: voc_split1_all,
    VOC_SPLIT1_5: voc_split1_all,
    VOC_SPLIT1_10: voc_split1_all,
    
    VOC_SPLIT2_1: voc_split2_all,
    VOC_SPLIT2_2: voc_split2_all,
    VOC_SPLIT2_3: voc_split2_all,
    VOC_SPLIT2_5: voc_split2_all,
    VOC_SPLIT2_10: voc_split2_all,
    
    VOC_SPLIT3_1: voc_split3_all,
    VOC_SPLIT3_2: voc_split3_all,
    VOC_SPLIT3_3: voc_split3_all,
    VOC_SPLIT3_5: voc_split3_all,
    VOC_SPLIT3_10: voc_split3_all,
}



if __name__ == "__main__":
    print("COCO_2017_SPLIT_1 (seen)", SEEN_CLS_DICT[COCO_2017_SPLIT_1])
    print("COCO_2017_SPLIT_1 (unseen)", [c for c in ALL_CLS_DICT[COCO_2017_SPLIT_1] if c not in SEEN_CLS_DICT[COCO_2017_SPLIT_1]])