_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "checkpoints/coco/10shot_ExAU-seed0/model_0004799.pth"
  MASK_ON: False
  BACKBONE:
    FREEZE: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: False
  ROI_HEADS:
    NUM_CLASSES: 80
    FREEZE_FEAT: True
    CLS_DROPOUT: True
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.01
    NAME: "CommonalityROIHeadsKnowledgeGuidedCL"
    OUTPUT_LAYER: "DoubleFastRCNNOutputLayers"
    MEMORY: True
    AUGMENTATION: False
    SEMANTIC: True
    WARMUP_DISTILL: 1000
DATASETS:
  TRAIN: ("removecoco14_trainval_all_10shot_seed0", )
  TEST: ('coco14_test_all',)
  TWO_STREAM: True
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
  STEPS: (4800,)
  MAX_ITER: 8000
  CHECKPOINT_PERIOD: 200
  WARMUP_ITERS: 0
TEST:
  PCB_ENABLE: True
  PCB_MODELPATH: "ImageNetPretrained/torchvision/resnet101-5d3b4d8f.pth"
  EVAL_PERIOD: 200
KGC:
  SHOTS: 10
  CONTAINER: 1
  FEATURE_DIM: 128
  KNOWLEDGE_MATRIX: "KnowledgeMatrix/text_relationship/coco/coco-word-embedding.npy"
  TAU: 0.2
  COEF: 0.01
COUNTERFACTUAL:
  OPERATOR: True
  START_ITER: 800
  ERASE_THRESHOLD: 0.8
  VISUALIZATION: False
  COUNTER_NUMBER: 5
  ERASE_RATE: 0.05
  ERASE_METHOD: "random"
OUTPUT_DIR: "checkpoints/coco/10shot_ExAU"